apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kogito
spec:
  template:
    metadata:
      name: kogito-v1
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/serverless-orchestration/kogito
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace